spring.application.name=career-accelerator

spring.datasource.url=jdbc:mysql://HOST:PORT/defaultdb
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
rapidapi.key=${RAPIDAPI_KEY}
server.port=${PORT:8081}